const Map<String, String> nameMap = {
  "FP": "Fuel pump",
  "FRP": "Fuel Rail Pressure",
  "FRPD": "Fuel Rail Pressure - Desired",
  "FRPDLP": "Desired fuel pressure (low pressure)",
  "FRPS": "Fuel Rail Pressure Sensor",
  "FRP_LRS": "Fuel Rail Pressure - Low Range Sensor",
  "EQ_RAT11": "Equivalence Ratio (Lambda) (Bank 1, Sensor 1)",
  "TIP_PRS-Boost": "Measured Boost at Throttle Inlet Pressure Sensor",
  "TP": "Throttle Position",
  "TP2": "Throttle Position Sensor 2",
  "ACT": "Air Charge Temperature",
  "AECPB1": "Actual Exhaust Camshaft Position Bank 1",
  "AICPB1": "Actual Intake Camshaft Position Bank 1",
  "APP1 [APP_D]": "Accelerator Pedal Position D",
  "APP2 [APP_E]": "Accelerator Pedal Position E",
  "APP_D": "Accelerator Pedal Position D",
  "APP_E": "Accelerator Pedal Position E",
  "BAP": "Boost Absolute Pressure - Raw sensor input voltage",
  "BARO": "Barometric pressure",
  "BOO2": "Brake Pressure Applied",
  "CPP": "clutch pedal position",
  "DECPB1": "Desired Exhaust Camshaft Position Bank 1",
  "DICPB1": "Desired Intake Camshaft Position Bank 1",
  "ECT": "Engine coolant temperature",
  "ECT_V": "Engine coolant temperature sensor voltage",
  "FUELSYS": "Fuel System Status (Open/Closed Loop)",
  "GEAR_N_OFFSET": "Gear Neutral Sensor Offset",
  "GEAR_N_OFF_LRN": "Gear Neutral Sensor Offset Learning Status",
  "IAT": "Intake Air Temperature",
  "IATS": "Intake Air Temperature Sensor",
  "LOAD": "Calculated Load Value",
  "LOAD_ABS": "Absolute Load Value",
  "LONGFT1": "Long term fuel trim 1",
  "LONGFT12": "Long Term Fuel Trim (Bank 1, Sensor 2)",
  "MAF": "Mass Air Flow",
  "MAINECUV": "Main ECU voltage supply",
  "MAP": "Manifold absolute pressure sensor",
  "MAP_V": "Manifold absolute pressure sensor",
  "O2S11": "Heated Exhaust Gas Oxygen Sensor (bank 1, sensor 1)",
  "O2S11_CUR": "Exhaust Gas Oxygen Sensor Current Bank 1 Sensor 1",
  "O2S11_IMPED": "O2S11 sensor impedance is expressed as a voltage.",
  "O2S12": "Heated Exhaust Gas Oxygen Sensor (bank 1, sensor 2)",
  "O2S12.STFT": "Short Term Fuel Trim (Bank 1, Sensor 2)",
  "O2S12.VOLT": "Heated Exhaust Gas Oxygen Sensor (bank 1, sensor 2)",
  "RPM": "Engine Revolutions Per Minute",
  "SHRTFT1": "Short term fuel trim 1",
  "THTRC": "Thermostat Heater Control",
  "TPSVS1": "Throttle Position Sensor Voltage - Sensor 1",
  "TP_B": "Throttle Position Sensor 2",
  "TP_REL": "Relative Throttle Position",
  "TURBO_WGATE": "Turbocharger Wastegate",
  "VCT_EXH_DC1": "Exhaust B Camshaft Position Duty Cycle Bank 1",
  "VCT_INT_DC1": "Intake A Camshaft Position Duty Cycle Bank 1",
  "VSS": "Vehicle Speed"
};
